name: Build and Release on Demand

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      
      - name: Build for Linux
        run: |
          GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build -ldflags '-w -s -buildid=' -o bin/goss-linux
          tar -czvf bin/goss-linux.tar -C bin goss-linux
      
      - name: Build for Windows
        run: |
          GOARCH=amd64 GOOS=windows CGO_ENABLED=0 go build -ldflags '-w -s -buildid=' -o bin/goss-win64.exe
          zip -j bin/goss-win64.zip bin/goss-win64.exe
      
      - name: Upload Linux binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: goss-linux.tar
          path: bin/goss-linux.tar
      
      - name: Upload Windows binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: goss-win64.zip
          path: bin/goss-win64.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: false
      
      - name: Download Linux binary
        uses: actions/download-artifact@v2
        with:
          name: goss-linux.tar
          path: bin
      
      - name: Download Windows binary
        uses: actions/download-artifact@v2
        with:
          name: goss-win64.zip
          path: bin
      
      - name: Upload Linux binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/goss-linux.tar
          asset_name: goss-linux.tar
          asset_content_type: application/gzip
      
      - name: Upload Windows binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/goss-win64.zip
          asset_name: goss-win64.zip
          asset_content_type: application/zip
